/** Login Mutations types**/
export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const LOGOUT = 'LOGOUT';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILED = 'LOGOUT_FAILED';

/**Authentication Mutation types**/
export const REGISTER = 'REGISTER';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';
export const REGISTER_FAILED = 'REGISTER_FAILED';

/** User profile Mutation types **/
export const PROFILE = 'PPROFILE';
export const PROFILE_SUCCESS = 'PROFILE_SUCCESS';
export const PROFILE_FAILED = 'PROFILE_FAILED';
export const PROFILE_ERROR = 'PROFILE_ERROR';

/** User profile update mutation types **/
export const PROFILE_UPDATE = 'PROFILE_UPDATE';
export const PROFILE_UPDATE_SUCCESS = 'PROFILE_UPDATE_SUCCESS';
export const PROFILE_UPDATE_FAILED = 'PROFILE_UPDATE_FAILED';
export const PROFILE_UPDATE_ERROR = 'PROFILE_UPDATE_ERROR';

/** Repayment Schedule Mutation types **/
export const REPAYMENT_SCHEDULE = 'REPAYMENT_SCHEDULE';
export const REPAYMENT_SCHEDULE_SUCCESS = 'REPAYMENT_SCHEDULE_SUCCESS';
export const REPAYMENT_SCHEDULE_ERROR = ' REPAYMENT_SCHEDULE_ERROR ';
export const REPAYMENT_SCHEDULE_FAILED = 'REPAYMENT_SCHEDULE_FAILED';

export const REPAYMENT_SCHEDULES = 'REPAYMENT_SCHEDULES';
export const REPAYMENT_SCHEDULES_SUCCESS = 'REPAYMENT_SCHEDULES_SUCCESS ';
export const REPAYMENT_SCHEDULES_ERROR = ' REPAYMENT_SCHEDULES_ERROR';
export const REPAYMENT_SCHEDULES_FAILED = 'REPAYMENT_SCHEDULES_FAILED';


export const SAVE_REPAYMENT_SCHEDULE = 'SAVE_REPAYMENT_SCHEDULE';
export const SAVE_REPAYMENT_SCHEDULE_SUCCESS = 'SAVE_REPAYMENT_SCHEDULE_SUCCESS';
export const SAVE_REPAYMENT_SCHEDULE_ERROR = 'SAVE_REPAYMENT_SCHEDULE_ERROR ';
export const SAVE_REPAYMENT_SCHEDULE_FAILED = 'SAVE_REPAYMENT_SCHEDULE_FAILED';

export const GET_INDICATORS = 'GET_INDICATORS';
export const GET_INDICATORS_SUCCESS = 'GET_INDICATORS_SUCCESS';
export const GET_INDICATORS_ERROR = 'GET_INDICATORS_ERROR';
export const GET_INDICATORS_FAILED = 'GET_INDICATORS_FAILED';

export const GET_INDICATORS_SOURCE = 'GET_INDICATORS_SOURCE';
export const GET_INDICATORS_SOURCE_SUCCESS = 'GET_INDICATORS_SOURCE_SUCCESS';
export const GET_INDICATORS_SOURCE_ERROR = 'GET_INDICATORS_SOURCE_ERROR';
export const GET_INDICATORS_SOURCE_FAILED = 'GET_INDICATORS_SOURCE_FAILED';

export const GET_SECTORS = 'GET_SECTORS';
export const GET_SECTORS_SUCCESS = 'GET_SECTORS_SUCCESS';
export const GET_SECTORS_ERROR = 'GET_SECTORS_ERROR';
export const GET_SECTORS_FAILED = 'GET_SECTORS_FAILER';

export const GET_CURRENT_RELEASES = "GET_CURRENT_RELEASES";
export const GET_CURRENT_RELEASES_SUCCESS = "GET_CURRENT_RELEASES_SUCCESS";
export const GET_CURRENT_RELEASES_FAILLED = "GET_CURRENT_RELEASES_FAILLED";
export const GET_CURRENT_RELEASES_ERROR = "GET_CURRENT_RELEASES_ERROR";

export const GET_DISAGGREGATIONS = "GET_DISAGGREGATIONS";
export const GET_DISAGGREGATIONS_SUCCESS = "GET_DISAGGREGATIONS_SUCCESS";
export const GET_DISAGGREGATIONS_FAILLED = "GET_DISAGGREGATIONS_FAILLED";
export const GET_DISAGGREGATIONS_ERROR = "GET_DISAGGREGATIONS_ERROR";

export const GET_DISAGGREGATIONS_VALUES = "GET_DISAGGREGATIONS_VALUES";
export const GET_DISAGGREGATIONS_VALUES_SUCCESS = "GET_DISAGGREGATIONS_VALUES_SUCCESS";
export const GET_DISAGGREGATIONS_VALUES_FAILLED = "GET_DISAGGREGATIONS_VALUES_FAILLED";
export const GET_DISAGGREGATIONS_VALUES_ERROR = "GET_DISAGGREGATIONS_VALUES_ERROR";


export const GET_LOGINS_VALUES = "GET_LOGINS_VALUES";
export const GET_LOGINS_VALUES_SUCCESS = "GET_LOGINS_VALUES_SUCCESS";
export const GET_LOGINS_VALUES_FAILED = "GET_LOGINS_VALUES_FAILLED";
export const GET_LOGINS_VALUES_ERROR = "GET_LOGINS_VALUES_ERROR";

export const GET_MAINLAND_VALUES = "GET_MAINLAND_VALUES";
export const GET_MAINLAND_VALUES_SUCCESS = "GET_MAINLAND_VALUES_SUCCESS";
export const GET_MAINLAND_VALUES_FAILLED = "GET_MAINLAND_VALUES_FAILLED";
export const GET_MAINLAND_VALUES_ERROR = "GET_MAINLAND_VALUES_ERROR";

export const GET_PERIODTYPES_VALUES = "GET_PERIODTYPES_VALUES";
export const GET_PERIODTYPES_VALUES_SUCCESS = "GET_PERIODTYPES_VALUES_SUCCESS";
export const GET_PERIODTYPES_VALUES_FAILLED = "GET_PERIODTYPES_VALUES_FAILLED";
export const GET_PERIODTYPES_VALUES_ERROR = "GET_PERIODTYPES_VALUES_ERROR";

export const GET_PRIVILEGE_VALUES = "GET_PRIVILEGE_VALUES";
export const GET_PRIVILEGE_VALUES_SUCCESS = "GET_PRIVILEGE_VALUES_SUCCESS";
export const GET_PRIVILEGE_VALUES_FAILLED = "GET_PRIVILEGE_VALUES_FAILLED";
export const GET_PRIVILEGE_VALUES_ERROR = "GET_PRIVILEGE_VALUES_ERROR";

export const GET_PUBLICATIONS_VALUES = "GET_PUBLICATIONS_VALUES";
export const GET_PUBLICATIONS_VALUES_SUCCESS = "GET_PUBLICATIONS_VALUES_SUCCESS";
export const GET_PUBLICATIONS_VALUES_FAILLED = "GET_PUBLICATIONS_VALUES_FAILLED";
export const GET_PUBLICATIONS_VALUES_ERROR = "GET_PUBLICATIONS_VALUES_ERROR";

export const GET_RURALS_VALUES = "GET_RURALS_VALUES";
export const GET_RURALS_VALUES_SUCCESS = "GET_RURALS_VALUES_SUCCESS";
export const GET_RURALS_VALUES_FAILLED = "GET_RURALS_VALUES_FAILLED";
export const GET_RURALS_VALUES_ERROR = "GET_RURALS_VALUES_ERROR";

export const GET_TOTALFEMALE_VALUES = "GET_TOTALFEMALE_VALUES";
export const GET_TOTALFEMALE_VALUES_SUCCESS = "GET_TOTALFEMALE_VALUES_SUCCESS";
export const GET_TOTALFEMALE_VALUES_FAILLED = "GET_TOTALFEMALE_VALUES_FAILLED";
export const GET_TOTALFEMALE_VALUES_ERROR = "GET_TOTALFEMALE_VALUES_ERROR";
