# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build

on:
  push:
    branches: [ master ]
 
env:
  GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
  MY_GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm cache verify
    - run: npm cache clean -f
    - run: rm -rf node_modules package-lock.json 
    - run : npm install -g npm
    - run: npm install --save core-js@^3
    - run: npm i --save
    - run: npm run production
    - name: Deploy to gihub pages 🚀
      uses: JamesIves/github-pages-deploy-action@4.1.0
      with:
        token: ${{ secrets.GITHUBTOKEN }}
        branch: gh-pages # The branch the action should deploy to.
        folder: dist # The folder the action should deploy.

